---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: frontend-permissive-ports
    run_list:
      - recipe[iptables-patterns::frontend_permissive_ports]
    attributes:

  - name: whitelist-ip-ports
    run_list:
      - recipe[iptables-patterns::whitelist_ip_ports]
    attributes:
      iptables-patterns:
        firewalls:
          - test
      iptables-test:
        tcp_ports:
          - 22
          - 80
        udp_ports:
          - 1090
        firewalled_chains:
          - INPUT
          - FORWARD
        whitelist_action: RETURN
        whitelist_ipv4_addresses:
          - '1.2.3.4'
          - '5.6.7.8'
          - '10.0.2.2'
        whitelist_ipv6_addresses:
          - '::1'
