name 'iptables-patterns'
maintainer 'Inviqa UK LTD'
maintainer_email 'kevans@inviqa.com'
license 'apachev2'
description 'Installs/Configures iptables-patterns'
long_description 'Installs/Configures iptables-patterns'
version '0.1.0'
